apiVersion: v1
kind: Pod
metadata:
  name: volapp
  labels:
    name: volapp
spec:
  containers:
  - name: volapp-cnt
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
    - name: volapp-vol
      mountPath: "/config/secret"
      readOnly: true
  volumes:
  - name: volapp-vol
    secret:
      secretName: mysecret
      

