apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    env:
    - name: NAME
      valueFrom:
        secretKeyRef:
          key: username
          name: mysecret
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          key: password
          name: mysecret
