---
apiVersion: v1
kind: Pod
metadata:
  name: memory-pod2
  namespace: jitsingh
spec:
  containers:
  - name: memory-container
    image: nginx
    resources:
      requests:
        memory: "100Mi"
        cpu: "100Mi"
      limits:
        memory: "100Mi"
        cpu: "100Mi"
