apiVersion: v1
kind: Pod
metadata:
  name: example-pod
  namespace: jitsingh
spec:
  containers:
    - name: example-pod-container
      image: quay.io/sunnyconcise/jenkins
      resources:
        requests:
          memory: "100Mi"
        limits:
          memory: "200Mi"
      command: ["ls"]
      args: ["-la"]

\]      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
