apiVersion: v1
kind: Pod
metadata:
  name: cm-pod-env
  labels:
    name: cm-pod-env
spec:
  containers:
  - name: cm-pod-env-cnt
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    env:
    - name: NAME
      valueFrom:
        configMapKeyRef:
          name: my-cm
          key: name
    - name: PHONE
      valueFrom:
        configMapKeyRef:
          key: phone
          name: my-cm
