apiVersion: v1
kind: Pod
metadata:
  name: cm-pod
  labels:
    name: cm-pod
spec:
  containers:
  - name: cm-pod-ctn
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
    - name: cm-vol
      mountPath: "/config"
      readOnly: true
  volumes:
  - name: cm-vol
    configMap:
      name: my-cm
